In [29]:
import pandas as pd

In [30]:
set1 = pd.read_csv('/home/puja/Downloads/movie_metadata.csv')
print set1.shape
set1.head(3)

(5043, 28)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

In [32]:
# v is the number of votes for the movie
# m is the minimum votes required to be listed in the chart
# R is the rating for the movie
# C is the mean vote across the whole report

C = set1['imdb_score'].mean()
print C

6.442137616498116

In [33]:
m = set1['num_voted_users'].quantile(0.90)
print m

216562.0

In [34]:
# Filter out all qualified movies into a new DataFrame
q_movies = set1.copy().loc[set1['num_voted_users']>=m]

print q_movies.shape

(505, 28)

In [35]:
# Function that computes the weighted rating for each movie
def weighted_rating(x, m=m, C=C):
    v = x['num_voted_users']
    R = x['imdb_score']
    return (v/(v+m)*R) + (m/(v+m)*C)

In [36]:
q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

In [37]:
q_movies = q_movies.sort_values('score', ascending=False)

# Print the top 15 movies
q_movies[['movie_title', 'num_voted_users', 'imdb_score', 'score']].head(15)

,movie_title,num_voted_users,imdb_score,score
1937,The Shawshank Redemption,1689764,9.3,8.975342
3466,The Godfather,1155770,9.2,8.764793
66,The Dark Knight,1676169,9.0,8.707335
3355,Pulp Fiction,1324680,8.9,8.554642
339,The Lord of the Rings: The Return of the King,1215718,8.9,8.528369
97,Inception,1468200,8.8,8.496917
683,Fight Club,1347461,8.8,8.473519
836,Forrest Gump,1251222,8.8,8.452113
2837,The Godfather: Part II,790926,9.0,8.450181
270,The Lord of the Rings: The Fellowship of the R...,1238746,8.8,8.449130
1874,Schindler's List,865020,8.9,8.407869
654,The Matrix,1217752,8.7,8.359093
340,The Lord of the Rings: The Two Towers,1100446,8.7,8.328729
2051,Star Wars: Episode V - The Empire Strikes Back,837759,8.8,8.315685
3024,Star Wars: Episode IV - A New Hope,911097,8.7,8.266387